# Generated by Django 4.2 on 2023-09-15 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, verbose_name='Name')),
                ('logo', models.ImageField(upload_to='company', verbose_name='Logo')),
                ('subtitle', models.TextField(max_length=300, verbose_name='SubTitle')),
                ('fb_link', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('tw_link', models.URLField(blank=True, null=True, verbose_name='Twitter')),
                ('yt_link', models.URLField(blank=True, null=True, verbose_name='Youtube')),
                ('phone', models.TextField(blank=True, max_length=45, null=True, verbose_name='Phone')),
                ('email', models.TextField(blank=True, max_length=45, null=True, verbose_name='Email')),
                ('address', models.TextField(blank=True, max_length=150, null=True, verbose_name='Address')),
                ('ios_app', models.TextField(blank=True, max_length=150, null=True, verbose_name='IOS')),
                ('android_app', models.TextField(blank=True, max_length=150, null=True, verbose_name='Android')),
                ('call_us', models.TextField(blank=True, max_length=150, null=True, verbose_name='Call US')),
                ('email_us', models.TextField(blank=True, max_length=150, null=True, verbose_name='Email US')),
            ],
        ),
    ]
