# Generated by Django 4.2 on 2024-04-30 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='total_with_cupon',
            new_name='total_with_coupon',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='total_with_cupon',
            new_name='total_with_coupon',
        ),
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='FGDMF4HH', max_length=8, unique=True),
        ),
    ]
