# Generated by Django 4.2 on 2024-07-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_rename_total_with_cupon_cart_total_with_coupon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='KLKFF9E5', max_length=8, unique=True),
        ),
    ]
