# Generated by Django 4.2 on 2024-07-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='H8C9IJ13', max_length=8, unique=True),
        ),
    ]
