# Generated by Django 4.2 on 2024-08-27 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='4A7C07K5', max_length=8, unique=True),
        ),
    ]
